apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-dev

namePrefix: dev-

commonLabels:
  environment: dev
  managed-by: kustomize

commonAnnotations:
  deployment.kubernetes.io/environment: dev

resources:
  - ../../base

patchesStrategicMerge:
  - kiali-patch.yaml

replicas:
  - name: kiali
    count: 1
